### ISSUE TITLE
ICM: Database Password has to be removed from values.yaml

### ISSUE THREAD

**Issue by csperrhake** [intershop/helm-charts#143]
https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

**Comment by A-Herold** [comment]
It would be a good idea, to use the same pattern as used by IOM. For any value, that has to be secured exist two values: <name> and <name>SecretKeyRef. This way a local installation can be easily done without the need to care about secrets. Any other installations are able to use secrets instead. Example:

`oms:
  # public URL of IOM
  # used internally by IOM for link generation.
  publicUrl:                       https://localhost
  # Shared secret for JWT creation / validation
  jwtSecret:                       length_must_be_at_least_32_chars
  jwtSecretKeyRef:                 {}
`

See also https://github.com/intershop/helm-charts/blob/main/charts/iom/docs/SecretKeyRef.rst

**Comment by Thomas-Bergmann** [comment]
There is also the option to use an azure managed identity and pod binding to avoid the db-password.
