### ISSUE TITLE
PWA: Reduce extensive logging of wget prefetch job

### ISSUE THREAD

**Issue by philippsauer** [intershop/helm-charts#399]
The cache prefetch job that has been introduced in pwa-main-0.5.0 creates a lot of unnecessary log output, as indicated below:
![image](https://github.com/intershop/helm-charts/assets/6233211/080537a3-6476-43ce-b08d-6b7532719837)

Problem description: When heavily used, the prefetch job creates huge amounts of logging information that are not required to verify that it is running properly. (e.g. 1 million lines per day)

Expected behavior: It should be possible to run prefetch job in a 'silent mode' preferably per configuration (e.g. with --quiet).

**Comment by shauke** [comment]
will be solved with PWA Helm Chart 0.8.0
(current project workaround development release `0.8.0-delta`)
