### ISSUE TITLE
PWA: Memcached should be cleared after PWA deployment

### ISSUE THREAD

**Issue by philippsauer** [intershop/helm-charts#410]
**Problem Description**: In release 0.8.0-delta, the shared cache does cache documents but does not cache static files. This leads to the following problem when deploying a new PWA release: Pages like '/home' are still cached and be therefore delivered to the user's browser. That document contains file references as follows:

```
<link rel="stylesheet" href="/styles.3d6129b9da98bdd2.css">
<script src="/main.b3cda4b20a9d371f.js" type="module"></script>
```
Unfortunately, the new PWA can not resolve those resources anymore. The page looks broken (no styles, js).

**Current work around**: Manually restart memcached container immediately before and after the PWA deployment process, to reduce the probability of invalid cache entries.

**Expected behavior**: After deploying a new PWA release, the current cache should be flushed automatically.

**Comment by dhhyi** [comment]
This problem sounds familiar and cannot be handled safely other that switching from rolling deploy to recreate strategy.
The PWA deployment was never made for rolling deploy.
Using Recreate strategy (configurable with #374) the deployment will be unavailable for a short time, but no faulty pages will be cached.

**Comment by shauke** [comment]
The current solution to this problem is the suggestion from Danilo with update strategy `Recreate`, that can now be achieved with PWA Helm Chart 0.8.0 and above.
